#!/bin/bash

function check_argv()
{
  if [[ -n $1 ]]; then
    echo "1";
    exit 1;
  else
    echo "0"
    exit 0;  
  fi

}

case $2 in
 hello) echo "hello"
 ;;
 toto) echo "toto"
 ;;
 *) echo "autre chose"
 ;;
esac


check_argv $1;
